### ISSUE TITLE
Upgrade references to the general text modules

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Qualification-DDI-CYP3A4#13]
Replace all refs to the general text modules with tag **v1.1**, e.g.
https://raw.githubusercontent.com/Open-Systems-Pharmacology/Qualification-text-modules/v1.1/OSPS_Introduction.md

**Comment by Yuri05** [comment]
@sfrechen is this fixed now?
(Please don't forget to include "fixes #NN" in the commit or PR description for automated issue closure)

**Comment by sfrechen** [comment]
@Yuri05 :

see here https://github.com/sfrechen/Qualification-DDI-CYP3A4/commit/f8eb9c6c7b637c3896e6d85ed937d36e5483fbe3
